services:
  nginx:
    image: nginx:alpine
    container_name: echelon_nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - backend
      - frontend
    networks:
      - echelon_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: echelon_backend
    restart: always
    ports:
      - "8000:8000"
    networks:
      - echelon_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: echelon_frontend
    restart: always
    networks:
      - echelon_network

networks:
  echelon_network:
    driver: bridge