[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.85"
fastembed = "4.3.0"
ollama-rs = { version = "0.2.2", features = ["stream"] }
qdrant-client = "1.12.1"
thiserror = "2.0.9"
tokio = { version = "1.42.0", features = ["rt-multi-thread"] }
uuid = { version = "1.11.0", features = ["fast-rng", "macro-diagnostics", "v4", "v5"] }
strum = "0.26.3"
strum_macros = "0.26.4"
fancy-regex = "0.14.0"
sqlx = { version = "0.8", features = ["runtime-tokio"] }
once_cell = "1.18"